package util;

import java.util.Iterator;
import java.util.stream.Stream;

/**
 * A generator is an infinite iterator that can be used to generate values on-the-fly.
 * It can be created from an iterable, an array, or a supplier function.
 * It can also be used to generate random values of various types.
 * <p>
 * The interface only have one method to implement: {@link #next()}. A Generator is always infinite,
 * so there is no {@code #hasNext()} method or similar checks.
 *
 * @param <T> The type of the elements generated by this generator.
 */
public interface Generator<T> extends Iterator<T> {
    /**
     * Always returns true, as a generator is infinite. This method is implemented
     * for {@code Generator} to work in for-each loops.
     * @return true
     */
    @Override
    default boolean hasNext(){ return true; }
    /**
     * Get the next element in the generator.
     * @return The next element in the generator.
     */
    @Override
     T next();
}
